//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailProcessingWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class clarityMailTable
    {
        public int sno { get; set; }
        public string fromalias { get; set; }
        public string toalias { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> mailDate { get; set; }
        public string ConversationID { get; set; }
        public string ConversationIndex { get; set; }
        public string ConversationTopic { get; set; }
    }
}
